//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_locquestion
    {
        public long locquestion_id { get; set; }
        public Nullable<long> location_id { get; set; }
        public Nullable<long> question_id { get; set; }
        public Nullable<System.DateTime> locquestion_cdate { get; set; }
        public string locquestion_active { get; set; }
        public Nullable<int> adminid_create { get; set; }
        public Nullable<int> adminid_update { get; set; }
    
        public virtual mas_question mas_question { get; set; }
        public virtual mas_location mas_location { get; set; }
    }
}
