//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mas_company()
        {
            this.mas_emp = new HashSet<mas_emp>();
            this.mas_route = new HashSet<mas_route>();
        }
    
        public long comp_id { get; set; }
        public string comp_name { get; set; }
        public string comp_desc { get; set; }
        public Nullable<bool> flag_internal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mas_emp> mas_emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mas_route> mas_route { get; set; }
    }
}
