//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mas_location()
        {
            this.mas_locquestion = new HashSet<mas_locquestion>();
            this.trn_answer = new HashSet<trn_answer>();
        }
    
        public long location_id { get; set; }
        public Nullable<long> route_id { get; set; }
        public string location_title { get; set; }
        public string location_desc { get; set; }
        public string location_active { get; set; }
        public Nullable<int> seq_number { get; set; }
        public Nullable<System.DateTime> location_cdate { get; set; }
        public Nullable<System.DateTime> location_udate { get; set; }
        public Nullable<int> adminid_create { get; set; }
        public Nullable<int> adminid_update { get; set; }
        public string qrcode1 { get; set; }
        public string qrcode1_status { get; set; }
        public string qrcode2 { get; set; }
        public string qrcode2_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mas_locquestion> mas_locquestion { get; set; }
        public virtual mas_route mas_route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_answer> trn_answer { get; set; }
    }
}
