//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mas_route()
        {
            this.mas_location = new HashSet<mas_location>();
            this.mas_question = new HashSet<mas_question>();
            this.trn_transaction = new HashSet<trn_transaction>();
        }
    
        public long route_id { get; set; }
        public string route_title { get; set; }
        public string route_desc { get; set; }
        public string route_active { get; set; }
        public Nullable<System.DateTime> route_cdate { get; set; }
        public Nullable<System.DateTime> route_udate { get; set; }
        public Nullable<int> adminid_create { get; set; }
        public Nullable<int> adminid_update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mas_location> mas_location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mas_question> mas_question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_transaction> trn_transaction { get; set; }
    }
}
