//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_emp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mas_emp()
        {
            this.trn_answer = new HashSet<trn_answer>();
        }
    
        public long emp_id { get; set; }
        public string emp_title { get; set; }
        public string emp_fname { get; set; }
        public string emp_surname { get; set; }
        public string emp_code { get; set; }
        public string emp_password { get; set; }
        public long emp_comp { get; set; }
        public string emp_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_answer> trn_answer { get; set; }
        public virtual mas_company mas_company { get; set; }
    }
}
