//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mas_admin
    {
        public int admin_id { get; set; }
        public string admin_user { get; set; }
        public string admin_password { get; set; }
        public Nullable<System.DateTime> admin_cdate { get; set; }
        public string admin_active { get; set; }
        public Nullable<long> company_id { get; set; }
    }
}
