//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QRCodeTourEntities : DbContext
    {
        public QRCodeTourEntities()
            : base("name=QRCodeTourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mas_emp> mas_emp { get; set; }
        public virtual DbSet<mas_location> mas_location { get; set; }
        public virtual DbSet<mas_locquestion> mas_locquestion { get; set; }
        public virtual DbSet<mas_question> mas_question { get; set; }
        public virtual DbSet<trn_answer> trn_answer { get; set; }
        public virtual DbSet<trn_transaction> trn_transaction { get; set; }
        public virtual DbSet<mas_route> mas_route { get; set; }
        public virtual DbSet<mas_admin> mas_admin { get; set; }
        public virtual DbSet<mas_company> mas_company { get; set; }
    }
}
