//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_hotkey
    {
        public long hotkey_id { get; set; }
        public string hotkey_code { get; set; }
        public Nullable<System.DateTime> hotkey_cdate { get; set; }
        public Nullable<System.DateTime> hotkey_expiredate { get; set; }
        public string hotkey_active { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<System.DateTime> hotkey_usedate { get; set; }
    }
}
