//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRT.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trn_transaction()
        {
            this.trn_answer = new HashSet<trn_answer>();
        }
    
        public long transaction_id { get; set; }
        public string transaction_comment { get; set; }
        public string transaction_picture { get; set; }
        public string session_id { get; set; }
        public Nullable<System.DateTime> transaction_cdate { get; set; }
        public Nullable<bool> transaction_answer { get; set; }
        public Nullable<long> location_id { get; set; }
        public Nullable<long> route_id { get; set; }
        public Nullable<long> emp_id { get; set; }
        public Nullable<long> round_number { get; set; }
    
        public virtual mas_location mas_location { get; set; }
        public virtual mas_route mas_route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_answer> trn_answer { get; set; }
    }
}
